import { StyleSheet } from "react-native";
import { spacing, typography, lightColors } from "@/shared/theme/theme";

export const createStyles = (colors: typeof lightColors, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: spacing.xxl,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  headerTitle: {
    color: colors.text,
    ...typography.headerTitle,
  },
  headerBtn: {
    color: colors.primary,
    ...typography.buttonText,
  },
  canvas: {
    flex: 1,
    alignItems: "center",
    position: "relative",
    marginTop: spacing.xxl,
  },
  emptyText: {
    color: colors.textMuted,
    ...typography.mutedText,
    marginTop: 100,
    textAlign: "center",
  },
  stickerWrapper: {
    width: 250,
    height: 250,
    marginBottom: spacing.xl,
    alignSelf: "center",
  },
  stickerImage: {
    width: "100%",
    height: "100%",
    borderWidth: 4,
    borderColor: colors.stickerBorder,
    backgroundColor: colors.surface,
    // Add subtle shadow for the "sticker" feel
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDark ? 0.5 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  bubble: {
    position: "absolute",
    backgroundColor: colors.bubbleBackground,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    // Asymmetric rounded corners for a "masking tape / speech bubble" feel
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 16,
    maxWidth: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDark ? 0.3 : 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  bubbleText: {
    color: colors.bubbleText,
    ...typography.bodyText,
  },
  reactionInputContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surfaceLight,
    padding: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  input: {
    flex: 1,
    backgroundColor: colors.surfaceOverlay,
    color: colors.text,
    padding: spacing.sm,
    borderRadius: 8,
    ...typography.bodyText,
  },
});
